*** Settings ***
Resource    ${CURDIR}/../resources/locators/component_locators.resource
Resource    ${CURDIR}/../resources/locators/login_locators.resource
Resource    ${CURDIR}/../resources/locators/product_list_page_locators.resource
Resource    ${CURDIR}/../resources/locators/product_detail_page_locators.resource
Resource    ${CURDIR}/../resources/locators/cart_page_locators.resource
Resource    ${CURDIR}/../resources/locators/checkout_page_locators.resource